version: "3.3"
services:
  api:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./api/:/var/www/html/"
    ports:
      - "3003:80"
  cli:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./cli/:/var/www/html/"
    ports:
      - "5005:80"
  shop:
    build:
      dockerfile: php.Dockerfilew
      context: .
    restart: always
    volumes:
      - "./shop/:/var/www/html/"
    ports:
      - "4004:80"
  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "30002:80"
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"

volumes:
  mysql-data:
