<?php
include_once(APP_PATH.'/views/header.php');
?>
<table class="table">
    <caption>Order Table</caption>
    <thead class="thead-dark">
        <tr>
            <th scope="col">order ID</th>
            <th scope="col">Name</th>
            <th scope="col">Address</th>
            <th scope="col">Product ID</th>
            <th scope="col">Quantity</th>
            <th scope="col">Status</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $value) {
            echo "<tr>
            <td scope=\"row\">$value[order_id]</td>
            <td>$value[name]</td>
            <td>$value[address]</td>
            <td>$value[product_id]</td>
            <td>$value[quantity]</td>
            <td>$value[status]</td>
            </tr>";
        }
        ?>
    </tbody>
</table>
